[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  framework = "#custom"
  command = "npm run dev:vite"
  targetPort = 5173
  port = 8888
  publish = "dist"
  autoLaunch = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["jimp", "sharp", "busboy"]

[build.environment]
  NODE_VERSION = "18.17.1" 